### ISSUE TITLE
No contact between two Lillygo

### ISSUE THREAD

**Issue by OrustEngineering** [dalathegreat/Battery-Emulator#277] opened 2024-04-30 14:31 UTC
Hi

We set up two Lillygo to be used on Solax X3 G2/G3 inverter and a Nissan Leaf 2012 battery.
Currently we do not use any precharging since the inverter has this.

The battery Lilly communicate with the battery but becomes red
![bild](https://github.com/dalathegreat/Battery-Emulator/assets/57301031/f3e54394-424b-4fc8-9a8a-1544c8564ea5)

NB! In this picture I run the LEaf battery in Lead accid mode wich also works perfect without battery emulator but wit less cell safte overview to the inverter.
![bild](https://github.com/dalathegreat/Battery-Emulator/assets/57301031/fbbdba14-e6a9-487f-af41-fe804351d2ee)

The inverter Lillygo i green comunicate with the inverter which accept but get SOC valu set to 0% 

It seems it is the communication beetween the boards that do not work.

![bild](https://github.com/dalathegreat/Battery-Emulator/assets/57301031/5e8e3ac7-5c03-4a8e-b210-0508f8449814)

It proberly someting dead simple but have not found it.

Please help

**Comment by Cabooman** [comment] 2024-04-30 20:11
This is a known issue with more recent SW (5.7+), please downgrade to 5.6.0 until we've had the chance to find the root cause

**Comment by dalathegreat** [comment] 2024-05-01 19:04
Fixed in 5.9.0 , thanks for troubleshooting this @Cabooman ! 

@OrustEngineering , please update to 5.9.0 https://github.com/dalathegreat/Battery-Emulator/releases/tag/v5.9.0

**Closed by dalathegreat** 2024-05-01 19:04 UTC

**Comment by Solarcs1979** [comment] 2024-05-03 15:05
Bra jobbat!
